### ISSUE TITLE
Don't warn every time on Run All (Modify)

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/flextools#11]
If I have 6 modules that don't modify the FLEx project and one that does, and I click Run All (Modify), I don't like getting 6 warnings for the modules that don't modify the project. Maybe these could just be Info messages or not given at all. See this video.
https://www.loom.com/share/892958a307874d0ca94a4e3b762ea865

**Comment by cdfarrow** [comment]
Yes, I see your point. I'll change it to an Info message once we decide what to do with the Run buttons. (#19)

**Comment by cdfarrow** [comment]
Changed to an Info message for version 2.2.0
