### ISSUE TITLE
Multi-select modules to run

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/flextools#13]
It would be nice to be able to ctrl-click to select certain modules to run and also click followed by shift-click. I often find my self wanting to have a bunch of modules ready to run, but only want to run maybe 4 out of 7.

**Comment by cdfarrow** [comment]
Good suggestion. I'll hopefully change this for the next version (2.1.2)

**Comment by bbryson** [comment]
Yes, I too would appreciate being able to select a subset of modules in a collection to run.
