### ISSUE TITLE
Add close button to the Collections dialog

### ISSUE THREAD

**Issue by cdfarrow** [cdfarrow/flextools#15]
It is confusing as-is about how to close the dialog with the new settings.

**Comment by rmlockwood** [comment]
I agree. It would be a nice improvement to have a Close button.

**Comment by bbryson** [comment]
Agree

**Comment by cdfarrow** [comment]
Added a Select button in the Collections group of buttons.
Also updated the Delete icon to a trash can to distinguish it from the Remove button.
