### ISSUE TITLE
Don't run succeeding modules when one fails.

### ISSUE THREAD

**Issue by bbryson** [cdfarrow/flextools#22]
If I am doing "Run All" on a lot of modules, and one of them throws an Error, currently the next modules still get run.  

However, if one failed, then the output of that is likely wrong, and the input to the next is likely wrong.  If all the modules run, so much scrolls by on the screen that I may not have noticed the Error message.  

If everything could stop on a failure, then I would have a chance to notice it and fix it before it goes on.

(This assumes that people write their modules so that fatal errors really are supposed to be fatal.  Currently some FLExTrans modules have "Errors" that should probably be "Warnings"--they don't need to be fatal.)

**Comment by cdfarrow** [comment]
Fixed for FlexTools 2.2.2
Added FTConfig.stopOnError: if True, then processing will stop after any module that outputs an error message.
