### ISSUE TITLE
Flextools fails to run (because of pythonnet 3.0)

### ISSUE THREAD

**Issue by MattGyverLee** [cdfarrow/flextools#23]
I'm a little sheepish to admit that after:

- a fresh install of Python 3.8.10 as suggested here https://github.com/cdfarrow/flexlibs/issues/6 
- successfully configuring the Windows Path variables to point to 3.8
- cloning flexTools and checking security settings (user/system have full access to the install folder)
- `pip install -r requirements.txt` (pointing to the right pip for 3.8)
- editing the .bat to `py -3.8 FlexTools\FlexTools.py %`* to get around the `ModuleNotFoundError: No module named 'clr'` error

I'm still having a hard time getting this version of FlexTools to work on my own machine. 

I get this on launch:

```
Traceback (most recent call last):
  File "FlexTools\FlexTools.py", line 569, in <module>
    main()
  File "FlexTools\FlexTools.py", line 562, in main
    form = FTMainForm()
  File "FlexTools\FlexTools.py", line 449, in __init__
    self.UIPanel = FTPanel(self.moduleManager,
  File "FlexTools\FlexTools.py", line 163, in __init__
    self.modulesList = UIModulesList.ModulesList(self.moduleManager,
  File "C:\Apps\flextools\FlexTools\UIModulesList.py", line 61, in __init__
    self.UpdateAllItems(contents)
  File "C:\Apps\flextools\FlexTools\UIModulesList.py", line 140, in UpdateAllItems
    self.DataSource = formattedItems
System.ArgumentException: Complex DataBinding accepts as a data source either an IList or an IListSource.
   at System.Windows.Forms.ListControl.set_DataSource(Object value)
```

I've just re-cloned again with no luck. Any ideas?

[flextools.log](https://github.com/cdfarrow/flextools/files/9787822/flextools.log)

Windows 11 22H2

**Comment by cdfarrow** [comment]
Oh, my apologies, @MattGyverLee. I made the fix to tie to pythonnet 2.5.2 on the develop branch, and forgot to do the right things when I published it. I'll get that sorted out asap.

**Comment by cdfarrow** [comment]
I've fixed flexlibs (v1.1.5 now), and released [FlexTools v2.1.2](https://github.com/cdfarrow/flextools/archive/refs/tags/v2.1.2.zip), which uses that and has a couple of other minor improvements.

**Comment by MattGyverLee** [comment]
FlexTools V2.1.2 works. Thanks!

**Comment by cdfarrow** [comment]
Thanks for the confirmation!
