### ISSUE TITLE
Provide setting for Run All to be disabled for some collections

### ISSUE THREAD

**Issue by cdfarrow** [cdfarrow/flextools#31]
For some collections it doesn't make sense to run them all, so a toggle to disable Run All on a per collection basis would be helpful.

**Comment by bbryson** [comment]
Did you say you had an idea for a hidden setting?  Some flag that we could set in the module by hand?  I agree that it doesn't need to be in the UI.

**Comment by cdfarrow** [comment]
Added a DisableRunAll option for collections. Configure it the collection's .ini file by adding these two lines at the top:
            [DEFAULT]
            DisableRunAll = True
