### ISSUE TITLE
Crash when module is manually removed from a collections ini file

### ISSUE THREAD

**Issue by rmlockwood** [cdfarrow/flextools#32]
In my FLExTrans installer, I'm removing a module from the tools collection (Settings). Now the ini file has a missing entry for what should be number 3 in the order. FlexTools should be able to deal with a gap in the numbering of the modules. I would expect number 4 to come right after number 2.
This is a bit of an urgent need so that FLExTrans can work properly after install.

[FLExTrans.Sense Linker Tool]
_order = 1

[FLExTrans.Live Rule Tester Tool]
_order = 2

[FLExTrans.Build Bilingual Lexicon]
_order = 4

**Comment by cdfarrow** [comment]
It now handles this situation.
I've also reimplemented the collections logic to not depend on the file structure, and also the ini files no longer use the _Order attribute. This will be included in the next release.
