### ISSUE TITLE
GUID searches should allow a partial GUID

### ISSUE THREAD

**Issue by WesPeacock** [cdfarrow/flextools#33]
In the same way that git allows a partial GUID when specifying a commit, the LCMBrowser should allow a search for a partial GUID.

If this is done, it might be good to note that some of the default FLEx lists break the assumption that GUIDs are supposed to be random. E.g.  The Morpheme Types CmPossibilityList (GUID:d7f713d8-e8cf-11d3-9764-00c04f186933) has the following list of possibilities some of which are the same for the first seven characters:
\<Possibilities>
\<objsur guid="56db04bf-3d58-44cc-b292-4c8aa68538f4" t="o"/>
\<objsur guid="d7f713da-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713db-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713dc-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713dd-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713de-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713df-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="c2d140e5-7ca9-41f4-a69a-22fc7049dd2c" t="o"/>
\<objsur guid="d7f713e1-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713e2-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713e4-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713e5-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713e7-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="d7f713e8-e8cf-11d3-9764-00c04f186933" t="o"/>
\<objsur guid="18d9b1c3-b5b6-4c07-b92c-2fe1d2281bd4" t="o"/>
\<objsur guid="af6537b0-7175-4387-ba6a-36547d37fb13" t="o"/>
\<objsur guid="3433683d-08a9-4bae-ae53-2a7798f64068" t="o"/>
\<objsur guid="a23b6faa-1052-4f4d-984b-4b338bdaf95f" t="o"/>
\<objsur guid="0cc8c35a-cee9-434d-be58-5d29130fba5b" t="o"/>
\</Possibilities>

**Comment by cdfarrow** [comment]
This repo is for FlexTools. You should report your request to the Fieldworks team.
