### ISSUE TITLE
Please note min and max python possible versions in release notes.

### ISSUE THREAD

**Issue by MattGyverLee** [cdfarrow/flextools#35]
When you install FLExTools (and FlexTrans, I created a sister issue there), I see that it offers to install a specific version of Python. I'm sure that is sufficient for people who don't use Python for other things. Unfortunately, the suggested version has NEVER been the version that I'm currently using for other projects and I want to know if I can continue using the version I have.

Because FLExTools (and FLExTrans) default to the Windows Path and don't allow specifying the specific installation at runtime, I basically have to stop working on other projects and roll back to an old version of Python while dealing with FlexTrans, and then reset my path and logout/restart to continue. I can sometimes tweak the config files to make it work one version higher, but this is trial and error checking to see if I can get the requirements. 

Preference 1: 
Please include in the release notes the minimum and maximum tested versions of Python. I assume that could be generated based on the requirements (cdfutils and FlexTools), which seem to be the sticking packages that don't update.
Preference 2 (requires code): 
Please allow me to choose a pre-existing python installation at install, and adjust scripts to point there.

**Comment by cdfarrow** [comment]
The FlexTools installation is just a zip file and doesn't install any version of Python--it is just the FlexTrans installer that does that to help ensure a stable environment for its users.

I'm a bit confused by your scenario. Last I looked, FlexTrans pins to the relevant Python version (`PYTHON = "py -3.8"`) in FlexTools.vbs, so if you have a later version installed, then they shouldn't interfere with each other.

If you are running FlexTools by itself, and your default Python is incompatible, then you can edit line 28 of scripts\FlextoolsCommands.vbs to override the Python version. E.g.:
`PYTHON = "py -3.11"`

BTW, I've made the updates needed for Python 3.12, so if that is your default installation, then you can re-run InstallOrUpdate.vbs to use 3.12. I've also added the Python versions to the notes for [2.3.0](https://github.com/cdfarrow/flextools/releases/tag/v2.3.0_2023.08.29)

**Comment by MattGyverLee** [comment]
Thanks for the update and the clarification. 

You can disregard my comment about the chosen version. Part of my confusion is that I mostly interact with the FlexTools embedded in FlexTrans, which offers to download Python during installation.
