### ISSUE TITLE
How do I access ServiceLocator? 

### ISSUE THREAD

**Issue by milekpl** [cdfarrow/flextools#36]
In my old code base, I had:

```
m_lexExampleFactory = `DB.db.ServiceLocator.GetInstance(ILexExampleSentenceFactory)
    m_translationFactory = DB.db.ServiceLocator.GetInstance(ICmTranslationFactory)
    m_possibilityFactory = DB.db.ServiceLocator.GetInstance(ICmPossibilityRepository)
 ```

DB has been removed as a parameter, but this no longer works when I replace 'DB' with the project parameter. How do I access the object cache?

**Comment by cdfarrow** [comment]
The new form is `project.project.ServiceLocator.GetInstance()`
