### ISSUE TITLE
Support for Fieldworks 9

### ISSUE THREAD

**Issue by somelinguist** [cdfarrow/flextools#6]
I'm assuming this will take a bit of work with the migration from FDO to LCM, is that correct?

**Comment by cdfarrow** [comment]
I'm working on this now.  Let me know if you are able to help test: flextoolshelp/gmail.com

**Comment by somelinguist** [comment]
Thanks for the info. I sent you an email. I'd be glad to help.

**Comment by milekpl** [comment]
Well, it does work for FLeX 9, but you need to change imports, in particular by changing COM interfaces to KernelInterfaces:

This is how it looked before
> from SIL.FieldWorks.Common.COMInterfaces import ITsString, ITsStrBldr

And what worked for me:

> from SIL.LCModel.Core.KernelInterfaces import ITsString, ITsStrBldr

**Comment by cdfarrow** [comment]
Fixed in flexlibs 1.1.1, which includes the old versions of the dlls that the Fieldworks libraries need. Tested and working with Fieldworks 9.1.11 in FLExTools 2.1.1.
